INSERT INTO smarttech.mainpage_offer (id, text, author_name, author_img, smartphone_id) VALUES (1, 'The best iPhone to date isn''t perfect. It''s got recycled looks and an eyesore of a notch, and it weighs as much as a phone and a half.

The high refresh rate implementation isn''t great in the early days, the powerhouse that is the A15 chipset tends to throttle a lot, and Apple still has work to do to put any meaning behind ''fast'' in its ''fast charging'' claims.

Then there''s the matter of iOS, which will forever remain a dealbreaker to some.
But it''s still the best iPhone ever, this 13 Pro Max. The display is properly gorgeous, and 120Hz support in apps will eventually pick up. Battery life is the longest we''ve seen on an iPhone and in its present state is among the best on a top-class smartphone. The chipset is plenty powerful to outpace anything even in its throttled state. And then, there''s the cameras - not quite the absolute best in existence, but they all just work and do so all the time, every time.

A new iPhone purchase is hardly ever rooted entirely in reason. But even setting emotion aside as best as we can, it''s hard to argue with what the iPhone 13 Pro Max has to offer.', 'Ali', '/media/images/admin.png', 4001);
INSERT INTO smarttech.mainpage_offer (id, text, author_name, author_img, smartphone_id) VALUES (2, 'If you''ve stayed with us that long, you''ve probably noticed we are conflicted about this Galaxy S21 Ultra.
It is the perfect smartphone on paper, even without a microSD expansion and a bundled charger.But we''ve had ups and downs while using it for the past week. By the end of this review, we realized the good stuff far outweighs the bad, and most of what we didn''t like could be fixed with an upcoming update.

The Galaxy S21 Ultra absolutely deserves its Ultra insignia - it has the best OLED screen with Wacom layer at that, the most powerful hardware, one of the largest batteries, good stereo speakers, and pretty advanced camera system. We were thoroughly impressed by the screen performance and the battery endurance, like the UI and the S-Pen features, and saw many good photos and videos saved by the various snappers.

We aren''t huge fans of the new industrial design - mostly how the camera on the back was made. The phone is large and slippery, making it very uncomfortable to handle without a case. The photo quality wasn''t always flagship-grade - Samsung needs to tone down its image processing even if it results in some noise or lesser dynamic range. We''ve always preferred images with natural-looking processing, and so far, both Apple and Samsung have failed us. Here''s hoping that at least Samsung does something in this direction with a software update.

If you are after the best and newest phone on the market - look no further - that''s the Galaxy S21 Ultra. It has its issues, but the overwhelmingly good features elsewhere and a patch or two will make up for everything. Samsung is definitely off to a good start this year with its Ultra!', 'Foad', '/media/images/admin.png', 4002);
INSERT INTO smarttech.mainpage_offer (id, text, author_name, author_img, smartphone_id) VALUES (3, 'Giving a "final verdict" on Samsung''s foldable devices has always been a real challenge. In fact, we could argue that with the Z Fold3 5G, Samsung has made things even harder on us, since it is undeniably and quantifiably better than its predecessor, while also technically cheaper and with that, still the best foldable around.

That is actually one of the few easy titles we can confidently slap on the Z Fold3 - it is the best, most feature-rich and all-encompassing foldable currently on the market. Samsung took the already excellent Z Fold2 and refined it further, adding things like IPX8 and S Pen support to the mix. It is, effectively, a representation of the very best this particular new form factor is currently capable of, and in an almost hard-to-believe turn of events, Samsung is actually selling it to users, not just showcasing it at an event somewhere. With aggressive pricing, pre-order bundles, deep carrier subsidies and a lower MSRP, no less. It''s almost surreal really.', 'Foad', '/media/images/admin.png', 4003);
INSERT INTO smarttech.mainpage_offer (id, text, author_name, author_img, smartphone_id) VALUES (4, 'The Galaxy A52 line, in our opinion, has successfully managed to hit the "sweet spot" within Samsung''s strong and compelling current Galaxy A lineup. The newest A52s 5G refresh has flawlessly executed a chipset upgrade, only bringing more value to the table. The Snapdragon 778G is not only all-around faster than the Snapdragon 750G it replaces, but it also brings along some nifty connectivity upgrades, namely Wi-Fi 6 and Bluetooth 5.2. Most importantly, though, it does so without harming or downgrading the other aspects of the Galaxy A52 and without really increasing its price tag either.

If you are after a great value-proposition from Samsung in 2021, or alternatively, really need an IP67 ingress protection rating for under EUR 450 at current pricing, then look no further than the Samsung Galaxy A52s 5G. Or, perhaps the A52, if you can find a good deal and can live with the trade-offs. It''s also important to note Samsung''s promise of extended software support on the Galaxy A line as an extra value add. You can expect 3 major OS updates, as well as 4 years of security patches.', 'Ali', '/media/images/admin.png', 4004);
INSERT INTO smarttech.mainpage_offer (id, text, author_name, author_img, smartphone_id) VALUES (5, 'Samsung often struggles to compete with the value-oriented brands in the lower market segments, and that''s the case with the Galaxy A12 we have here. It''s not a bad phone, and it excels in endurance, it takes decent pictures, and it looks good in the process. It''s also a Samsung, and the brand itself could make it more appealing than its actual merits.

But if you''re on a limited budget, is it really all that important what badge is on the back of your phone? Opting for one of the competitors will likely get you a superior overall package, and you might even save a little. If, however, you must absolutely get a Galaxy, the A12 is a reasonable compromise. It wouldn''t be our top choice for the money, though.', 'Ali', '/media/images/admin.png', 4005);
INSERT INTO smarttech.mainpage_offer (id, text, author_name, author_img, smartphone_id) VALUES (6, 'If the Redmi 9 is over your budget, there is an even cheaper version sold as Redmi 9A. It''s as big and with equally beefy battery, but it has lower screen resolution, weaker chipset, and inferior camera skills.

The Redmi 9A lacks fingerprint scanner and its base version comes with just 2GB of RAM. You can opt for better equipped versions with 3GB or even 6GB RAM, but then again - why not go for the Redmi 9 instead?

Anyway, the Redmi 9A is a good phone for its €99 price and it will do just fine for calls, emails, chats, social networks and web browsing. It''s a bit sluggish, but if you won''t be playing games, you''d be fine with it.', 'Foad', '/media/images/admin.png', 4006);
INSERT INTO smarttech.mainpage_offer (id, text, author_name, author_img, smartphone_id) VALUES (7, 'We loved the Poco X3 Pro, and you can easily tell that. There is hardly a better performer at that price level. And early birds can get one for as low as €199.

The Poco X3 Pro offers unbeatable flagship bang for some entry-level buck, but it also impresses with so much more - display, speakers, battery, charging, and even camera. This achievement is something for the history books, just like the first Poco F1''s was and the X3 Pro receives our outright recommendation.', 'Ali', '/media/images/admin.png', 4007);
INSERT INTO smarttech.mainpage_offer (id, text, author_name, author_img, smartphone_id) VALUES (8, 'The Mi 11 Lite turned out to be a good alternative to the Mi 11 flagship if you are on a limited budget. The Lite model keeps many of the Mi 11''s key features, of course, with a different interpretation. There is an HRR OLED screen, capable hardware with dependable battery life, loud stereo speakers, the camera is good for the class. Overall, the Mi 11 Lite is what a proper Lite version should be all about.

The in-house competition, however, is too strong, and we can''t recommend the Mi 11 Lite over any of the recent Xiaomi models. It''s not a bad phone, but there are simply better ones at the same or lower price.

It''s a great compact phone, but at this price level - it''s too expensive for its own good.', 'Ali', '/media/images/admin.png', 4008);
INSERT INTO smarttech.mainpage_offer (id, text, author_name, author_img, smartphone_id) VALUES (9, 'This one is for the fans, isn''t it? But if you aren''t one already, the Galaxy S20 FE may very well convert you - a Samsung flagship at the core at a friendlier price.

A few concessions had to be made for the lighter price tag and it''s almost as if the least expensive one bugs us the most - the charger dates back to the Galaxy Note4 times. The plastic back isn''t as classy as the glass one on higher-end Galaxies, though this could be a con or pro, depending on where you stand. For whatever reason, we''re not finding the FE''s 4K recording up to the S20 standard. And lastly, the selfie camera isn''t the best Samsung can offer.

But that''s about it. The Fan Edition may not be a truly top-tier device by the book, but it''s got the key markings of one with just the right corners cut to meet a more appealing price point. It then represents amazing value - for a Galaxy in particular, but also against competing offerings. It''s got our recommendation.', 'Foad', '/media/images/admin.png', 4009);
INSERT INTO smarttech.mainpage_offer (id, text, author_name, author_img, smartphone_id) VALUES (10, 'The iPhone 12 Pro Max is Apple''s mightiest iPhone on the market today. It employs the most massive iPhone screen ever. It has every new feature the company has come up with, and it''s wrapped in a premium body with a bold new design that brings a dash of nostalgia. Heck, even its outrageous price tag is a selling point for many potential customers.

The 12 Pro Max is not without its flaws. On the contrary - it''s doesn''t even bring enough worthy upgrades over the 11 Pro Max to justify a switch. Not only that, but they are cutting back some features and deliberately omitting others. No charger, no headphones, same camera quality generation after generation, no high refresh rate screen when everyone else has one, and no under-display fingerprint reader when everybody is forced to wear a mask.

Apple is certainly not a company to go with the trends. On the opposite, their success in doing things differently has turned them into a trend-setter. For any other company, any of these decisions would have led to a severe backlash. Yet, Apple''s mobile business is doing better than ever.

They''ve earned a special place in the customer''s hearts and minds by coming up with consistently polished products with great after-sales service, and of course, by supplementing all this effort with great marketing.', 'Ali', '/media/images/admin.png', 4010);
INSERT INTO smarttech.mainpage_offer (id, text, author_name, author_img, smartphone_id) VALUES (11, 'If you''re into long gaming without requiring the high / ultra quality this could be a good phone. Doesn''t heat up like other "flagship killer" wannabe. It''s light and its comfortable to hold for long gaming hours. Cores doesn''t really matter, it only matters if you''re lazy af.', 'Ali', '/media/images/admin.png', 4011);
INSERT INTO smarttech.mainpage_offer (id, text, author_name, author_img, smartphone_id) VALUES (12, 'Huawei''s attempt at predicting the future with the P smart 2021 isn''t entirely failed - it''s not a bad phone, and with the right carrier subsidy, could make a fine daily driver for a less demanding user. It''s got properly excellent battery life, a decent camera system, and a display that gets very accurate with a minor tweak.

But some issues prevent us from recommending the P smart 2021. First and foremost, that''s obviously the lack of Google Play Services - the Huawei AppGallery selection is wide and ever-growing, but it''s still no Play Store. The chipset might have been reasonably powerful in 2018, but there are better options today, sadly unavailable to Huawei for the same reason Google isn''t on board. The SoC is probably responsible for the lack of 4K video and stabilization in 1080p, and that''s one too many drawbacks.

Then comes the fact that there are several handsets at the P smart''s price point that beat it in one key area or another, or even across the board. All things considered, unless your carrier makes a particularly exciting offer on the Huawei P smart 2021, our advice would be to look elsewhere.', 'Foad', '/media/images/admin.png', 4012);
INSERT INTO smarttech.mainpage_offer (id, text, author_name, author_img, smartphone_id) VALUES (13, 'While the Galaxy M51 was a clearly positioned marathon runner, the M52 5G takes a more balanced approach. Replacing the 7,000mAh battery with a 5,000mAh one may have robbed the new model of record-breaking endurance numbers, but it''s still one of the longest-lasting phones in its class, especially for this performance level. It''s all the more impressive an achievement when you consider how light and thin the handset is, something you couldn''t call its predecessor.

A most welcome upgrade in the display department sees the M52 5G packing a 120Hz screen, and aside from its somewhat battery-unfriendly stubbornness to maintain that high refresh rate in video playback, it''s a properly good display. The M51 was a capable midrange cameraphone, and the new model improves on that, particularly in the stills department, be it day or night. It''s not a good choice for a video recorder, though, with stabilization in 4K missing from its feature set.

Some generational developments may raise a few eyebrows, like the scrapping of the headphone jack (come on, even the A52s has one!), or the relegation of the microSD slot to a ''shared'' status. The single speaker isn''t helping its case either, and bundling a charger that can''t max out the phone''s capability for power input is a bit annoying.

All in all, however, we''d say that the Galaxy M52 is a well-rounded and competent handset with essentially no deal-breaking faults at a reasonable price. Regional differences in the numbers may make it a better deal in one place than another, so it wouldn''t hurt if you make some price comparisons in your local market context. Either way, the Galaxy M52 is a solid device.', 'Foad', '/media/images/admin.png', 4013);
INSERT INTO smarttech.mainpage_offer (id, text, author_name, author_img, smartphone_id) VALUES (14, 'Samsung has made the new Galaxy A-series phones hard to ignore. The A72 packs a feature set that brings it closer than ever to flagship territory.

The Galaxy A72 rocks an eye-catching and trendy design. It''s got a solid build with IP67 ingress protection. It might not be made of premium materials but still feels great to touch.

The 6.7-inch display has gorgeous colors and great brightness output thanks to modern AMOLED tech.

Now for some downsides, or at least deficiencies on the Galaxy A72: A display with a faster refresh rate and HDR video capabilities would have been great to see. Speaking of high display refresh rates, we can''t help but think of high fps gaming - a challenge for the Snapdragon 720G chipset. While it is not holding back the current feature set of the A72 in any way, faster silicon is now readily available in the mid-range space. A higher-grade chipset would have meant some trendy extras like Wi-Fi 6 or 6e and perhaps Bluetooth 5.1 but there are now missing.', 'Ali', '/media/images/admin.png', 4014);
INSERT INTO smarttech.mainpage_offer (id, text, author_name, author_img, smartphone_id) VALUES (15, 'It''s an iPhone, a special edition at that, so it will sell in millions, break records, and score some impressive revenue for Apple. And there is not a single test, video, review, or an opinion online to change that. Unless it battery starts exploding, the X is bound to be a blockbuster. Bound by blood if you will even.

So if the iPhone X is indeed the start of a new generation of iPhones, we already can''t wait to see what''s next. That''s the thing about it - the unrealized potential and the promises it holds for the future are much more exciting than the product we have in our hands today.', 'Foad', '/media/images/admin.png', 4015);
INSERT INTO smarttech.mainpage_offer (id, text, author_name, author_img, smartphone_id) VALUES (16, 'The small iPhone is dead! Long live the small iPhone! That is pretty much the deal with every new iPhone, and it was about time to happen with the SE generation. The second SE is a small and powerful phone, water-resistant and beautiful, with a capable camera and great iOS support.

The new iPhone SE is the cheapest iPhone right now, but also one of the cheapest flagship-like phones on the market if we are to compare bang for the buck. The only things you must do to like it is to embrace the bezels and buy a fast charger.', 'Ali', '/media/images/admin.png', 4016);
INSERT INTO smarttech.mainpage_offer (id, text, author_name, author_img, smartphone_id) VALUES (17, 'The Redmi Note 10 Pro is so likable, and it aced our tests, so it''s really hard to find any faults. This one easily becomes our current favorite bang for the buck offer and one of the easiest "go for it" we''ve written in a while.

The Redmi Note 10 Pro is not a perfect smartphone, but its imperfections are easily forgivable and forgettable. And while this Note wasn''t made to be a flagship killer, it is shrinking the gap and may soon be breathing down their necks.', 'Foad', '/media/images/admin.png', 4017);
INSERT INTO smarttech.mainpage_offer (id, text, author_name, author_img, smartphone_id) VALUES (18, 'Xiaomi knows how to make a good phone, and the Poco M3 Pro 5G follows the same successful recipe - it packs the best features money can buy you at €179, with 5G being one of the highlights. We did like the 90Hz LCD screen - it was always smooth, bright enough and with great contrast. All four cameras do nice photos, you can play games mostly satisfactory, and the battery life is amazing.

The Poco M3 Pro 5G is not the fastest chap, that is for sure - the GPU is unimpressive, the charging is not that fast, there are no popular features like dual speakers or 4K video capturing. But right now, 5G is expensive, so we can only imagine where a large chunk of the budget went.

The Poco M3 Pro 5G is not a phone for everyone, obviously. If you want to join the first people getting access to 5G and all that instantaneous web load times, it''s probably the cheapest way in. If 5G doesn''t matter that much, just look elsewhere.', 'Ali', '/media/images/admin.png', 4018);
INSERT INTO smarttech.mainpage_offer (id, text, author_name, author_img, smartphone_id) VALUES (19, 'Huawei''s AppGallery is expanding, sure, but the tempo is far from rapid and it will take some time before it even begins to feel like a proper app store. But, if you are fine with sideloading stores and apps, the Honor 9X Pro will work for you just fine.

We did like the Honor 9X Pro a lot once we removed ourselves from the "It''s a Google''s world" mindset. There is life after Google even if Huawei is yet to really prove that. And Amazon and the likes do help. We only hope for the video streaming issues to be resolved and this phone might actually be quite usable.

Then again, if you consider Google''s apps and the Play Store a must-have, then the Honor 9X Pro will not cut it, no matter what we or Honor has to say.', 'Foad', '/media/images/admin.png', 4019);
INSERT INTO smarttech.mainpage_offer (id, text, author_name, author_img, smartphone_id) VALUES (20, 'The $190 Nokia G20 is a unique suggestion for its clean Android. It has a large 720p screen and a good enough chip to handle such resolution, plus it shows potential with its quad-camera (wide+ultrawide+depth+macro). The 5,050mAh battery seems excellent for the job, too.

The Nokia G20 isn''t the fastest phone and its screen sharpness isn''t ideal, but it''s quite cheap and Android 11 is a treat you''d probably like.', 'Foad', '/media/images/admin.png', 4020);
