# Generated by Django 3.2.9 on 2021-12-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimgurl',
            name='img_url',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='smartphoneimgurl',
            name='img_url',
            field=models.CharField(max_length=2083),
        ),
    ]
