# Generated by Django 3.2.9 on 2021-12-08 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_auto_20211208_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='mainPage.user'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainPage.user'),
        ),
    ]
