# Generated by Django 3.2.9 on 2021-12-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_auto_20211213_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_primary',
            field=models.CharField(max_length=2083, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='img_primary',
            field=models.CharField(max_length=2083, null=True),
        ),
    ]
