# Generated by Django 3.2.9 on 2021-12-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_avatar_upload',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
