# Generated by Django 3.2.9 on 2021-12-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_auto_20211216_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_avatar',
            field=models.CharField(default='https://png.pngtree.com/png-vector/20190710/ourmid/pngtree-user-vector-avatar-png-image_1541962.jpg', max_length=2083),
        ),
    ]
