# Generated by Django 3.2.9 on 2021-12-09 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_auto_20211208_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphonedescription',
            name='smartphone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.smartphone'),
        ),
        migrations.AlterField(
            model_name='smartphoneimgurl',
            name='smartphone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.smartphone'),
        ),
    ]
