# Generated by Django 3.2.9 on 2021-12-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0006_alter_user_img_avatar_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
