# Generated by Django 3.2.9 on 2022-01-07 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0008_auto_20211223_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author_name', models.CharField(max_length=128)),
                ('author_img', models.CharField(max_length=2083)),
                ('smartphone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='mainPage.smartphone')),
            ],
        ),
    ]
