# Generated by Django 3.2.9 on 2022-01-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0009_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='cons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='pros',
            field=models.TextField(blank=True, null=True),
        ),
    ]
